// Generated by gencpp from file beginner_tutorials/my_srv.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MY_SRV_H
#define BEGINNER_TUTORIALS_MESSAGE_MY_SRV_H

#include <ros/service_traits.h>


#include <beginner_tutorials/my_srvRequest.h>
#include <beginner_tutorials/my_srvResponse.h>


namespace beginner_tutorials
{

struct my_srv
{

typedef my_srvRequest Request;
typedef my_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct my_srv
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::my_srv > {
  static const char* value()
  {
    return "b8a2aab5099fa54e0eb1247d552c20ed";
  }

  static const char* value(const ::beginner_tutorials::my_srv&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::my_srv > {
  static const char* value()
  {
    return "beginner_tutorials/my_srv";
  }

  static const char* value(const ::beginner_tutorials::my_srv&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::my_srvRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::my_srv >
template<>
struct MD5Sum< ::beginner_tutorials::my_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::my_srv >::value();
  }
  static const char* value(const ::beginner_tutorials::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::my_srvRequest> should match
// service_traits::DataType< ::beginner_tutorials::my_srv >
template<>
struct DataType< ::beginner_tutorials::my_srvRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::my_srv >::value();
  }
  static const char* value(const ::beginner_tutorials::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::my_srvResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::my_srv >
template<>
struct MD5Sum< ::beginner_tutorials::my_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::my_srv >::value();
  }
  static const char* value(const ::beginner_tutorials::my_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::my_srvResponse> should match
// service_traits::DataType< ::beginner_tutorials::my_srv >
template<>
struct DataType< ::beginner_tutorials::my_srvResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::my_srv >::value();
  }
  static const char* value(const ::beginner_tutorials::my_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MY_SRV_H
